# Generated by Django 2.1.2 on 2019-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shohin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日付')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日付')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('kataban', models.CharField(max_length=50, verbose_name='型番')),
                ('shohin_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('zaikosu', models.IntegerField(verbose_name='在庫数')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('memo', models.TextField(max_length=1000, verbose_name='メモ')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shohin',
            unique_together={('belong_user', 'kataban')},
        ),
    ]
