# Generated by Django 2.1.2 on 2019-02-23 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nohin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('nohin_date', models.DateField(verbose_name='納品日')),
                ('totalPrice', models.IntegerField(verbose_name='合計金額')),
                ('memo', models.TextField(max_length=1000, null=True, verbose_name='メモ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NohinDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('kataban', models.CharField(max_length=50, verbose_name='型番')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('nohin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_table.Nohin', verbose_name='納品')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='shohin',
            name='memo',
            field=models.TextField(max_length=1000, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='shohin',
            name='regist_date',
            field=models.DateTimeField(verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='shohin',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='更新日時'),
        ),
    ]
