# Generated by Django 2.1.2 on 2019-02-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_table', '0002_auto_20190223_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nohin',
            old_name='totalPrice',
            new_name='total_price',
        ),
    ]
