# Generated by Django 2.1.2 on 2019-02-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_table', '0003_auto_20190223_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('company_name', models.CharField(max_length=50, verbose_name='会社名')),
            ],
        ),
        migrations.AddField(
            model_name='nohin',
            name='nohinsaki',
            field=models.CharField(default=1, max_length=50, verbose_name='納品先'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('belong_user', 'company_name')},
        ),
    ]
