# Generated by Django 2.1.2 on 2019-07-06 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_table', '0005_auto_20190706_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='nohin',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='nohin',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='nohindetail',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='nohindetail',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='shohin',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='shohin',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新日時'),
        ),
    ]
