# Generated by Django 2.1.2 on 2019-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_table', '0006_auto_20190706_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='regist_date',
            field=models.DateTimeField(verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='nohin',
            name='regist_date',
            field=models.DateTimeField(verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='nohin',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='nohindetail',
            name='regist_date',
            field=models.DateTimeField(verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='nohindetail',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='shohin',
            name='regist_date',
            field=models.DateTimeField(verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='shohin',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='更新日時'),
        ),
    ]
